# Generated by Django 4.2.4 on 2023-10-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
