# Generated by Django 4.2.4 on 2023-10-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0002_alter_client_options_alter_client_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия'),
        ),
    ]
