# Generated by Django 4.2.4 on 2023-10-10 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=250, verbose_name='тело сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='тема сообщения'),
        ),
    ]
