# Generated by Django 4.2.4 on 2023-10-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_newsletter', '0002_newsletter_is_active_alter_newsletter_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlog',
            name='server_answer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ответ сервера'),
        ),
    ]
